/* Generated By:JavaCC: Do not edit this line. YalToJvmTreeConstants.java Version 6.0_1 */
public interface YalToJvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTVOID = 1;
  public int JJTFUNCTION = 2;
  public int JJTPARAMS = 3;
  public int JJTVAR = 4;
  public int JJTFUNCTIONBODY = 5;
  public int JJTINST = 6;
  public int JJTASSIGN = 7;
  public int JJTLHS = 8;
  public int JJTRHS = 9;
  public int JJTARRAYSIZE = 10;
  public int JJTTERM = 11;
  public int JJTEXPRTEST = 12;
  public int JJTWHILE = 13;
  public int JJTIF = 14;
  public int JJTCALL = 15;
  public int JJTARGUMENTLIST = 16;
  public int JJTARGUMENT = 17;
  public int JJTARRAYACCESS = 18;
  public int JJTSCALARACCESS = 19;
  public int JJTINDEX = 20;


  public String[] jjtNodeName = {
    "Module",
    "void",
    "Function",
    "Params",
    "Var",
    "FunctionBody",
    "Inst",
    "Assign",
    "Lhs",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=a6ea3761ac7a9500e7e964e277e76ec1 (do not edit this line) */
