/* Generated By:JavaCC: Do not edit this line. YalToJvmTreeConstants.java Version 6.0_1 */
public interface YalToJvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTPARAMS = 3;
  public int JJTSTOREARRAY = 4;
  public int JJTSTOREVARIABLE = 5;
  public int JJTFUNCTIONBODY = 6;
  public int JJTBODY = 7;
  public int JJTVOID = 8;
  public int JJTASSIGNEMENT = 9;
  public int JJTARRAYSIZE = 10;
  public int JJTTERM = 11;
  public int JJTCONDITION = 12;
  public int JJTWHILE = 13;
  public int JJTIF = 14;
  public int JJTCALL = 15;
  public int JJTARGUMENTLIST = 16;
  public int JJTARGUMENT = 17;
  public int JJTARRAYACCESS = 18;
  public int JJTSCALARACCESS = 19;
  public int JJTINDEX = 20;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "Function",
    "Params",
    "StoreArray",
    "StoreVariable",
    "FunctionBody",
    "Body",
    "void",
    "Assignement",
    "ArraySize",
    "Term",
    "Condition",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=2550d83cce8e5bd9ffabc66a85341acd (do not edit this line) */
