/* Generated By:JavaCC: Do not edit this line. YalToJvmTreeConstants.java Version 6.0_1 */
public interface YalToJvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTVOID = 1;
  public int JJTFUNCTION = 2;
  public int JJTPARAMS = 3;
  public int JJTVAR = 4;
  public int JJTFUNCTIONBODY = 5;
  public int JJTWHILEBODY = 6;
  public int JJTIFBODY = 7;
  public int JJTELSEBODY = 8;
  public int JJTASSIGNEMENT = 9;
  public int JJTRHS = 10;
  public int JJTARRAYSIZE = 11;
  public int JJTTERM = 12;
  public int JJTCONDITION = 13;
  public int JJTWHILE = 14;
  public int JJTIF = 15;
  public int JJTCALL = 16;
  public int JJTARGUMENTS = 17;
  public int JJTARGUMENT = 18;
  public int JJTARRAYACCESS = 19;
  public int JJTSCALARACCESS = 20;
  public int JJTINDEX = 21;


  public String[] jjtNodeName = {
    "Module",
    "void",
    "Function",
    "Params",
    "Var",
    "FunctionBody",
    "WhileBody",
    "IfBody",
    "ElseBody",
    "Assignement",
    "Rhs",
    "ArraySize",
    "Term",
    "Condition",
    "While",
    "If",
    "Call",
    "Arguments",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=ab3d0f58fdddc7094b0ae790d3f2079d (do not edit this line) */
