/* Generated By:JavaCC: Do not edit this line. YalToJvmTreeConstants.java Version 6.0_1 */
public interface YalToJvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTGLOBAL = 1;
  public int JJTVOID = 2;
  public int JJTFUNCTION = 3;
  public int JJTPARAMS = 4;
  public int JJTARRAY = 5;
  public int JJTSCALAR = 6;
  public int JJTFUNCTIONBODY = 7;
  public int JJTWHILEBODY = 8;
  public int JJTIFBODY = 9;
  public int JJTELSEBODY = 10;
  public int JJTASSIGNEMENT = 11;
  public int JJTRHS = 12;
  public int JJTARRAYSIZE = 13;
  public int JJTTERM = 14;
  public int JJTCONDITION = 15;
  public int JJTWHILE = 16;
  public int JJTIF = 17;
  public int JJTCALL = 18;
  public int JJTARGUMENTS = 19;
  public int JJTARGUMENT = 20;
  public int JJTARRAYACCESS = 21;
  public int JJTSCALARACCESS = 22;
  public int JJTINDEX = 23;


  public String[] jjtNodeName = {
    "Module",
    "Global",
    "void",
    "Function",
    "Params",
    "Array",
    "Scalar",
    "FunctionBody",
    "WhileBody",
    "IfBody",
    "ElseBody",
    "Assignement",
    "Rhs",
    "ArraySize",
    "Term",
    "Condition",
    "While",
    "If",
    "Call",
    "Arguments",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=da7b3c3f2bc27fa729c1818d7ade2d20 (do not edit this line) */
