/* Generated By:JavaCC: Do not edit this line. YalToJvmTreeConstants.java Version 6.0_1 */
public interface YalToJvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTMODULEBODY = 1;
  public int JJTFUNCTION = 2;
  public int JJTPARAMS = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTSCALARELEMENT = 5;
  public int JJTFUNCTIONBODY = 6;
  public int JJTSTMT = 7;
  public int JJTASSIGN = 8;
  public int JJTLHS = 9;
  public int JJTRHS = 10;
  public int JJTARRAYSIZE = 11;
  public int JJTTERM = 12;
  public int JJTEXPRTEST = 13;
  public int JJTWHILE = 14;
  public int JJTIF = 15;
  public int JJTCALL = 16;
  public int JJTARGUMENTLIST = 17;
  public int JJTARGUMENT = 18;
  public int JJTARRAYACCESS = 19;
  public int JJTSCALARACCESS = 20;
  public int JJTINDEX = 21;


  public String[] jjtNodeName = {
    "Module",
    "ModuleBody",
    "Function",
    "Params",
    "ArrayElement",
    "ScalarElement",
    "FunctionBody",
    "Stmt",
    "Assign",
    "Lhs",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=239bd63106070305c4e1ea1b4d80edcf (do not edit this line) */
